# Precommit hooks.
# install using `pre-commit install`
# skip using `git commit -m "message" --no-verify`
default_stages: [pre-commit, pre-push]

repos:
  # Default provided pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # v6.0.0 # pragma: allowlist secret
    hooks:
    - id: check-added-large-files
      exclude_types: [markdown, yaml, json]
    - id: check-merge-conflict
    - id: check-yaml
    - id: detect-private-key # detects the presence of private keys
    - id: end-of-file-fixer
    - id: fix-byte-order-marker
    - id: name-tests-test
      args: [--pytest-test-first]
    - id: trailing-whitespace
      exclude: |
          (?x)(
            ^dev_utils/ |
            ^config/ |
            ^.github/
          )

  # Yelp pre-commit hooks to detect secrets
  - repo: https://github.com/Yelp/detect-secrets
    rev: 01886c8a910c64595c47f186ca1ffc0b77fa5458  # v1.5.0 # pragma: allowlist secret
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        exclude: |
          (?x)(
            ^docs/environment_setup.md
          )

  # Ruff pre-commit hook
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 65dbdb59d2f2d9c3bdc343c566821ad3319ddaa3  # v0.16.3 # pragma: allowlist secret
    hooks:
      # Run the linter.
      - id: ruff-check
        types_or: [ python, pyi ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi ]

  # Bandit pre-commit hook to detect vulnerabilities
  - repo: https://github.com/PyCQA/bandit
    rev: 92ae8b82fb422a639f0ed8d99e96cea769594e08 # 1.9.4 # pragma: allowlist secret
    hooks:
      - id: bandit
        args: ["--recursive", "--severity-level=all", "--confidence-level=all", "--exclude", "tests,.venv"]

  # Local hooks
  - repo: local
    hooks:

      - id: restricted-filenames
        name: Check commits for restricted file extensions
        entry: Looking for extensions that are not allowed
        language: fail
        files: .*\.(csv|feather|xlsx|zip|hdf5|h5|txt|xml|hd|parquet)

      - id: prepare_commit_msg
        name: Prepare commit message
        entry: dev_utils/pre-commit_helpers/prepare_commit_msg.py
        stages: [prepare-commit-msg]
        language: system
        exclude: |
          (?x)(
            ^dev_utils/ |
            ^config/ |
            ^.gitlab/
          )
        exclude_types: [markdown, yaml]
