name: Build and test
on: [push, workflow_dispatch]

env:
  PROJECT_NAME: business_surveys_results_methods
  ARTIFACTORY_PYPI_REPO: LR_EPDS_pypi
permissions:
  contents: read
  

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        # remember to update this if we have a later version of uv
        enable-cache: true

    - name: Set up Python 3.11.0
      uses: actions/setup-python@v6
      with:
        python-version: "3.11.0"

    # Re-lock since Github Actions can't access Artifactory
    - name: Setup and install dependencies
      run: |
        uv lock --default-index https://pypi.org/simple
        uv sync

    - name: Run unit tests and coverage report
      run: |
        source .venv/bin/activate
        pytest tests/ --cov --cov-report term --verbose

  
